name: Bitcoin Test

on: [push]

jobs:
  bitcoin-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Bitcoin Core
        run: sudo apt-get install -y bitcoind

      - name: Configure Bitcoin Core
        run: |
          mkdir -p ~/.bitcoin
          echo "server=1" >> ~/.bitcoin/bitcoin.conf
          echo "regtest=1" >> ~/.bitcoin/bitcoin.conf
          echo "rpcallowip=127.0.0.1" >> ~/.bitcoin/bitcoin.conf
          echo "rpcbind=127.0.0.1" >> ~/.bitcoin/bitcoin.conf
          echo "rpcport=18443" >> ~/.bitcoin/bitcoin.conf

      - name: Start Bitcoin Daemon
        run: bitcoind -daemon -regtest

      - name: Wait for bitcoind to start
        run: sleep 10

      - name: Check Bitcoin Node Status
        run: bitcoin-cli -regtest getblockchaininfo

      - name: Create Wallet
        run: bitcoin-cli -regtest createwallet "btrustwallet"
